anaconda/anaconda-client

- binstar_client/commands/upload.py
This PR fixes two minor typos I spotted in the help documentation returned by `binstar upload --help`.
> Fix typos in 'binstar upload' command-line parser help strings.

- binstar_client/inspect_package/pypi.py
10.1 of binstar is giving us the following traceback: 
```
Traceback (most recent call last):
File "/Users/coleb/.virtualenvs/binstar_client/bin/binstar", line 9, in <module>
load_entry_point('binstar==0.10.1', 'console_scripts', 'binstar')()
File "/Users/coleb/.virtualenvs/binstar_client/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 94, in main
description=__doc__, version=version)
File "/Users/coleb/.virtualenvs/binstar_client/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
return args.main(args)
File "/Users/coleb/.virtualenvs/binstar_client/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 168, in main
package_attrs, release_attrs, file_attrs = get_attrs(package_type, filename)
File …
```
> PyPI upload of sdist package appears broken

- binstar_client/inspect_package/conda.py
The way to determine the sub-directory is now read from the new 'subdir' key in the `info/index.json` file of the conda package, and still defaults to determine the value from the `platform` and `arch` keys.
This is in particular useful to support the new noarch packages which conda-build can create, see https://github.com/conda/conda-build/pull/317 (merged into master, but not yet released).
I have tested to upload a noarch package to binstar, and it works!!!  Conda is already looking for the optional `noarch` subdirectory as of conda 3.8.4.
> read new 'subdir' key from index, and default to existing way

- binstar_client/commands/upload.py
- binstar_client/inspect_package/conda_installer.py
- binstar_client/utils/__init__.py
- binstar_client/utils/detect.py
This will allow `binstar upload` to upload linux and osx installers without any extra args. 
This will allow binstar-build to run automated installer scripts.
> Upload installers

- setup.py
Users can now run `conda server ...` in place of `binstar ...`. This change is backwards compatible.
cc @asmeurer @csoja @ilanschnell
> Alias conda-server to binstar

- binstar_client/commands/_files.py
- binstar_client/commands/_release.py
- example-packages/pypi/package1/__init__.py
It may be desirable in some cases to import print_function if running under python2, but this should be at least syntactically valid.
> Fix print statements to be python3-compatible

- binstar_client/utils/notebook/uploader.py
Now versions will look like:
I believe we need the hour/minute information to avoid having problems with notebooks with the same version
@srossross @LilaHickey
> Improve notebook's versions readability #171

- binstar_client/utils/notebook/tests/test_uploader.py
- binstar_client/utils/notebook/uploader.py
Once the notebook's been uploaded it has `-ipynb` at the end. Example: `https://anaconda.org/malev/notebook-ipynb`
Remove `-ipynb` from the end of the name before creating the project.
> Notebook's name won't have ipynb at the end anymore

- binstar_client/utils/notebook/downloader.py
```
➜  tmp  binstar notebook download sean/conda_data-ipynb
Using binstar api site https://api.anaconda.org
destination path 'conda_data.ipynb' already exists.
➜  tmp  binstar notebook download sean/conda_data-ipynb --force
Using binstar api site https://api.anaconda.org
sean/conda_data-ipynb has been downloaded as conda_data.ipynb.
```
@srossross @LilaHickey
> Shows message instead of exception in #177

- .binstar.yml
- requirements.txt
Jupyter is a big metapackage and we only need nbformat
> Using nbformat

- binstar_client/commands/login.py
Fixes the error message that had anaconda.org hard-coded.  Refers to issue #205.
> change anaconda.org to AS instance in err msg

- binstar_client/commands/authorizations.py
fix link to examples section on using tokens
> fix link to examples section on using tokens

- binstar_client/requests_ext.py
- conda.recipe/meta.yaml
- requirements.txt
- setup.py
Request body must only use bytes, rather than unicode objects.
Using `six.b` together with `unicode_literals` does not work correctly -
on Python 2.7, `six.b` is a pass-through (i.e. `lambda x: x`). If we are
using `unicode_literals`, then we should explicitly encode or use
`b'strings'` where appropriate.
Fixes #222, anaconda-server/anaconda-build#108
> Fix package upload using PyOpenSSL

- binstar_client/inspect_package/pypi.py
- binstar_client/inspect_package/tests/test_pypi.py
Instead of using the entire file path.
If you upload an egg with the path `/tmp/has-dash/test_package34-0.3.1-py2.7.egg`, it will have a detected python_version of `0.3.1` and platform of `py2.7`, since it is counting dashes in the entire file path, instead of just the filename.
> Use basename to detect platform and package name

- binstar_client/commands/logout.py
- binstar_client/scripts/cli.py
* catch unauthorized error when performing logout.
* don't prompt for interactive login when stdin is not a tty
> Fix: no longer prompted to login on logout

- binstar_client/utils/__init__.py
From the debug information from @drf5n in Anaconda-Server/docs.anaconda.org#145
```
[DEBUG] Found login token: /Users/drf/Library/Application Support/binstar/https%3A%2F%2Fapi.anaconda.org.token
[DEBUG] (u'This domain requires token authentication', 401)
```
The only way I could reproduce this error was to create an empty token file. For any other token value you should get `[DEBUG] (u'Invalid Token', 401)`
This PR introduces a check that the token file is not empty and removes the file after that.
> Possible fix for invalid token file

- binstar_client/commands/upload.py
- binstar_client/requests_ext.py
- conda.recipe/meta.yaml
- requirements.txt
- setup.py
Removes restriction on requests version, generates a warning when a user tries to upload a package that triggers the bug.
I'm not sure if it should still show the whole traceback, since it's a known issue...  perhaps in case the OpenSSL error is not the one we are warning about?
Issue #256
> PR: Requests/PyOpenSSL version warning

- binstar_client/__init__.py
- binstar_client/commands/authorizations.py
- binstar_client/tests/test_authorizations.py
Related #224 
allows `anaconda auth` to pass the `-o` parameter to the server.
example:
`anaconda auth -r TestToken -o mytestorg`
> added fix to pass organization parameter if removing token from org

- binstar_client/tests/test_upload.py
- binstar_client/utils/detect.py
This fixes the error reported by Jasmine Sandhu in flowdock Tuesday, January 5:
```
> anaconda -V
anaconda Command line client (version 1.2.1)
> anaconda upload -t file bz-test-data.tgz 
Using Anaconda Cloud api site https://api.anaconda.org
extracting package attributes for upload ...
[ERROR] 
Traceback (most recent call last):
File "/Users/jsandhu/miniconda/bin/anaconda", line 6, in <module>
sys.exit(main())
File "/Users/jsandhu/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 87, in main
description=__doc__, version=version)
File "/Users/jsandhu/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 66, in binstar_main
return args.main(args)
File "/Users/jsandhu/miniconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line …
```
> add unused *args, **kwargs to file handler

- binstar_client/utils/__init__.py
@PeterDSteinberg I think this may allow anaconda-build to access private channels automatically, using the API token generated for the user that owns the package being built.
> Support reading API token from environment variable

- binstar_client/mixins/channels.py
Issue #204 
Order of the arguments was incorrect in the URL generation.
> Fix `channel --remove` command

- binstar_client/commands/package.py
Clarify that installing a private package requires authorized as well as authenticated access per discussion in https://github.com/Anaconda-Server/support/issues/19#event-531670734 .
> 'authenticated' -> 'authorized and authenticated'

- binstar_client/utils/__init__.py
> Typo in warning message

- binstar_client/commands/download.py
- binstar_client/commands/notebook.py
- binstar_client/commands/upload.py
Deprecate
`anaconda notebook upload`
Invite people to use:
`anaconda upload notebook.ipynb`
#295
> Upload notebooks with thumbnails

- binstar_client/inspect_package/conda.py
- binstar_client/utils/detect.py
I've been testing using conda for managing data dependencies (not just software deps). 
When the tar.bz2 files get large, the memory use and speed are intolerable. This makes minor changes to use the streaming tar stuff.
On my test case of a 780MB tar.bz2, it:
+ prevents a MemoryError on my laptop with 8GB of RAM (memory use after this PR is not noticeable)
+ takes the time to `determine_package_type` from 2 minutes to 0.05 seconds.
+ also speeds up extracting package attributes.
I'd like to make another PR to conda-build so that items are added to the tar file by order of size since likely we'll want to access the recipe.json and index.json frequently and quickly without incurring the penalty of decompressing all members of the tar file--with the idea that these JSON files will be the …
> reduce memory usage and improve speed by using streaming tar operations.

- binstar_client/requests_ext.py
See #256 
We should not issue this warning if they're using a newer version of requests.
> OpenSSL issue with requests is fixed in 2.9.1, stop warning

- binstar_client/commands/copy.py
> Fix --from-label, --to-label arguments to anaconda copy

- conda.recipe/build.sh
- conda.recipe/meta.yaml
the current conda recipe is failing in windows. They seem to be fixed now:
https://anaconda.org/binstar/binstar/builds/551
> Fixing conda recipe in windows

- binstar_client/__init__.py
- binstar_client/tests/test_packages.py
Related to https://github.com/Anaconda-Server/anaconda-server/pull/1662
I added some extra checks to get arguments via GET and refine the query based on `package_type`, `platform` and `type`, so I can query something like
**api.anaconda.org/packages/goanpeca?platform=linux-64&package_type=conda&type=app**
and receive something like:
```json
[
{
"conda_platforms": [
"None-None"
], 
"app_type": {
"v0.1.0b1": "desk"
}, 
"name": "conda-manager", 
"versions": [
"v0.1.0b1"
], 
"url": "http://api.None/packages/goanpeca/conda-manager", 
"app_entry": {
"v0.1.0b1": "conda-manager"
}, 
"package_types": [
"conda"
], 
"html_url": "http://None/goanpeca/conda-manager", 
"latest_version": "v0.1.0b1", 
"summary": "Graphical conda package manager with Spyder plugin integration", 
"public": true, …
```
> PR: Include optional args for packages api

- binstar_client/inspect_package/conda.py
This is the missing piece from #d299e183 that actually allows the command to break once it has found the info it needs. This prevents looping over all parts of the tar ball.
> break when all data from tarball is found

- binstar_client/utils/projects/tests/test_models.py
It looks like the unit test for #315 does not work reliably if the source is checked out somewhere else. In Anaconda Build, it ends up as "source". This was breaking the build.
> Tests should not depend on the directory the source is checked out as

- binstar_client/requests_ext.py
- binstar_client/tests/test_requests_ext.py
`requests_ext.MultiPartIO` should always return bytes.
> Fix encoding error in multipart io

- .binstar.yml
- conda.recipe/meta.yaml
Allow us to make dev builds of anaconda-client and upload them to anaconda.org/binstar/anaconda-client. @malev
> Change package name to anaconda-client for CI

- binstar_client/utils/__init__.py
Anyone running an internal Anaconda repo will be discombobulated by the
use of the word 'Cloud', which suggests that it's connecting to the
wider Internet.
See message in [Dev] email thread about this.
> Replace 'Anaconda Cloud' message on startup

- binstar_client/commands/upload.py
- binstar_client/requests_ext.py
- conda.recipe/meta.yaml
- requirements.txt
- setup.py
Since a fixed version of requests has been released for several months (see https://github.com/Anaconda-Platform/anaconda-client/pull/297), we can remove this cruft.
> Remove requests 2.8 warning

- LICENSE.md
- conda.recipe/meta.yaml
- setup.py
Fixes #340 
Add a `LICENSE` file, plus some extra metadata to the conda and pypi packages.
> Add license file

- binstar_client/commands/upload.py
Adding clarity in help text to denote that -u can be used for
organiziations as well.
> change to help text

- binstar_client/commands/config.py
- binstar_client/utils/conda.py
- binstar_client/utils/config.py
- binstar_client/utils/test/test_config.py
https://github.com/Anaconda-Platform/anaconda-server/issues/2826
https://github.com/Anaconda-Platform/anaconda-server/issues/2516
Allows `anaconda-client` to load configuration files from the conda prefix/root prefix.
> Load configuration from $PREFIX/.anacondarc

- binstar_client/utils/conda.py
- binstar_client/utils/test/test_conda.py
This crashed on Python 3 in an environment outside of envs/ directory,
which unfortunately happens during a conda package build.
> Finding conda root, decode the `conda info` output before JSON-parsing

- binstar_client/__init__.py
- binstar_client/commands/login.py
- binstar_client/commands/upload.py
- binstar_client/tests/test_login.py
- binstar_client/tests/test_upload.py
Closes #206 and #207 
Just displays a custom message when the api server returns a 404. Looks like this now:
> Better error message for the server not found exception

- binstar_client/tests/data/foo.ipynb
Latest anaconda_project gets upset about an empty notebook file
because it pokes in the notebook file for information.
(This is supposed to fix the build)
> Put some JSON in test notebook foo.ipynb

- binstar_client/utils/conda.py
Fixes #398 
Conda build creates a `conda.bat` that works as a symlink to a `conda.exe`. What i did is check which one exists and use that.
> trying with conda.bat if conda.exe doesn't exists

- README.md
We are about to edit https://docs.continuum.io/anaconda-repository/user/using so that it only shows the conda installation method. @abarto suggested having the alternate methods in the readme here but not on that docs page.
> add pip install info

- CHANGELOG.md
- binstar_client/__init__.py
Solves https://github.com/Anaconda-Platform/anaconda-server/issues/3000 adding `https://` when   necessary to domain
> Add `https://` to domain URL when is missing

- binstar_client/__init__.py
When adding a release we need to be sure we're sending a description, even if it's None. This PR fixes the case where `release_attrs` doesn't have `description`
> Fixed missing description issue

- CHANGELOG.md
- binstar_client/__init__.py
- binstar_client/commands/upload.py
When uploading a package we need to send the `package_types` attribute.
> sending package_types

- CHANGELOG.md
- binstar_client/commands/upload.py
Fixes [#4261](https://github.com/Anaconda-Platform/anaconda-server/issues/4261) 
It uses correct package type in logging info when uploading files
Upload a package/environment/notebook and verify that the correct package type is used on the info printed on screen
> Display correct package type when uploading files

- CHANGELOG.md
- binstar_client/__init__.py
We weren't sending the proper headers when the storage is located in the same server as the API.
> Using session to upload a package when the storage is in the same server as the api

- CHANGELOG.md
- binstar_client/commands/config.py
- binstar_client/utils/config.py
Closes #420 as it implements `ssl_verify` as a config value. 
`verify_ssl` still works but with less precedence than `ssl_verify`
> Using ssl_verify option as an alternative to verify_ssl

- CHANGELOG.md
- binstar_client/commands/copy.py
- binstar_client/mixins/package.py
- binstar_client/tests/test_copy.py
These options were already deprecated and it was confusing the users.
> Removed --from-channel and --to-channel

- CHANGELOG.md
- binstar_client/commands/upload.py
Closes [#4672](https://github.com/Anaconda-Platform/anaconda-server/issues/4672)
Log error message when uploading a package before raising exception
> Raise exception after logging error message

- CHANGELOG.md
- binstar_client/inspect_package/conda_installer.py
Changed the signature of the attribute extraction method so it doesn't blow when uploading installers.
> Fix installer detection

- CHANGELOG.md
- binstar_client/utils/yaml.py
- conda.recipe/meta.yaml
- requirements.txt
The whole ruamel.yaml vs ruamel_yaml is causing some issues with anaconda-server development environment. We're going back to PyYAML for the time being.
> Remove ruamel_yaml

- CHANGELOG.md
- binstar_client/__init__.py
A warning will be displayed when a response from the server contains the read only or lockdown header.
> Add support for read-only and lockdown headers

- CHANGELOG.md
- binstar_client/commands/config.py
- binstar_client/utils/test/test_config.py
- binstar_client/utils/yaml.py
Fixes #459. Adds support for a unicode tag (which shouldn't work in Py3).
https://github.com/ContinuumIO/anaconda-issues/issues/8605#issuecomment-366759140.
The client won't blow when it sees a unicode tag.
> Support unicode yaml tag.

- .travis.yml
- CHANGELOG.md
- binstar_client/inspect_package/ipynb.py
- binstar_client/inspect_package/tests/data/notebook-no-metadata.ipynb
- binstar_client/inspect_package/tests/test_ipynb.py
- binstar_client/tests/test_upload.py
- binstar_client/utils/notebook/__init__.py
- circle.yml
- runtests.sh
Closes https://github.com/Anaconda-Platform/anaconda-server/issues/4783.
This will read the metadata of the notebook during upload allowing updates to the summary on repo.
> Inspect notebook metadata on upload

- binstar_client/utils/config.py
Fix issues using legacy `get_binstar()` caused by incorrect argument order
cc @jakirkham 
cc @abarto
> fix for errorneous get_binstar()

- binstar_client/scripts/cli.py
I realized after I fixed this that it could be superseded by #507, but at least this one-line fix is so small it is easy to test and merge.
> Don't hide all uncaught exceptions

- binstar_client/utils/__init__.py
Python 3.9 has removed the deprecated fallback for Python 2.x
> fix: AttributeError: module 'base64' has no attribute 'encodestring'

- CHANGELOG.md
- binstar_client/utils/__init__.py
Introduction of a unified interface for `base64.encodestring`/`base64.encodebytes` for both python 2.7 and python 3+.
Fixes #555
> PR: Fix #555 - Upload - Fix of deprecated base64 functions usage

- binstar_client/__init__.py
- binstar_client/commands/download.py
- binstar_client/commands/remove.py
- binstar_client/commands/search.py
- binstar_client/commands/show.py
- binstar_client/commands/upload.py
- binstar_client/utils/appdirs.py
- binstar_client/utils/config.py
- binstar_client/utils/detect.py
- binstar_client/utils/pprint.py
Extensions and cleanups to better support r packages, as well as present "standard python" and "standard r" labels instead of "pypi"/"r".
Dev-tested on a linux-64 machine
> AC-116: better support for standard r packages

- CHANGELOG.md
- binstar_client/commands/upload.py
- tests/test_upload.py
When anaconda-client uploads a wheel, it uses the pypi compliant package name. This means it [replaces ‘_' and ‘.' with ‘-’](https://github.com/Anaconda-Platform/anaconda-client/blob/2893410fa23ccd14e514c945a1f0e744adc7cb83/binstar_client/inspect_package/pypi.py#L38-L40). The effect of this is that a separate package is created for any conda packages which have '.’ or '-’ in their name. 
It IS possible to pass the package name as an argument on upload.  However, if the package name that is passed as an argument does not exactly match the name that is normalized for pypi, anaconda-client throws an error:
```
π anaconda upload --package mkl_random --label wheels mkl_random-1.2.2-17-cp39-cp39-macosx_10_10_x86_64.whl
Using Anaconda API: http://localhost:4990/api
Using "foouser" as upload …
```
> AS-758: Allow path to upload whl with conda package name

- CHANGELOG.md
- binstar_client/commands/upload.py
- tests/test_upload.py
This PR is related to [this conda discussion](https://github.com/conda/infrastructure/discussions/649#discussioncomment-5398665). To sum up, it is not currently possible to upload a new distribution of the same version of a package and have the metadata from the new distribution be applied to the repository.  This story is about adding this capability as an upload option.
Here is the scenario this PR addresses:
1. A package is uploaded: `user_foo/package_bar/1.0.0`.
2. The package has certain `dev_url` and `doc_url` defined in the conda-build meta.yml. These values are reflected on the package's web page.
3. A new release is created with the same metadata (`doc_url`, `dev_url`): `user_foo/package_bar/1.1.0`.  At this point everything is still fine.
4. At some point, the metadata changes …
> AC-149: Use package metadata on upload

- binstar_client/utils/conda.py
- binstar_client/utils/config.py
If not in the base/root environment or a named environment use the CONDA_EXE variable to call conda and determine the root prefix. If this variable is not set, fall-back to a 'conda' command which may by on PATH.
When not on Windows set the creationflags parameter to 0.
Rename the CONDA_PREFIX variable to ENV_PREFIX which better represents the path.
fixes #643
> fix logic used to find CONDA_ROOT

- binstar_client/requests_ext.py
Vendor the deprecated `iter_fields` function from urllib3.
This function was removed from urllib3 in version 2.0.0
> vendor deprecated iter_fields function

- binstar_client/scripts/cli.py
Adds the ability for another package to replace the main CLI entrypoint function by defining the plugin entrypoint `anaconda_cli.main`. This allows us to maintain the `anaconda` entrypoint CLI inside `anaconda-client` for as long as we want, and also allows over-riding behavior and supporting additional plugins if another package implementing this plugin is installed into a user's environment.
This change should have no user impact in the case `anaconda-client` is upgraded without having a companion package implementing this plugin. In the design of the package implementing this plugin, we will take care to maintain compatibility and provide appropriate deprecation paths for users who happen to have both installed in an automated setting.
In the very rare case that a user accidentally has …
> feat: Allow main entrypoint plugin

- binstar_client/utils/config.py
There is a lot of copied code between binstar_client and conda when it comes to token management: loading, storing, and deleting. In theory, this is necessary because it should be possible to use anaconda-client _without_ conda. But the copying means that any mechanisms we might consider to enhance token management in conda will not be picked up in anaconda-client. For instance, for anaconda-ident, we are enabling conda to store tokens within its configuration mechanism. But this mechanism would then be unavailable to anaconda-client.
This PR attempts to drive towards correction by using `conda.gateways.anaconda_client` whenever it is installed in the same environment:
- `c.g.a. _get_binstar_token_directory()` overrides the `TOKEN_DIRS` determination
- `c.g.a.read_binstar_tokens()` is …
> use conda.gateways.anaconda_client for tokens possible

- binstar_client/inspect_package/conda.py
When a noarch package is built, `conda-build` currently sets the `arch` and `platform` fields to `null`. `rattler-build` does not even include them when a noarch package is built, as they are optional anyway (see https://docs.conda.io/projects/conda-build/en/stable/resources/package-spec.html#repo-si). This PR sets `arch` and `platform` to `null` instead of panicking if the fields are missing.
> Make `arch` and `platform` inside index.json optional

- binstar_client/utils/appdirs.py
- binstar_client/utils/config.py
In commit 9ce1897 the vendored appdirs=1.2.0 was replaced with the newer platformdirs implementation.
In appdirs=1.2.0 "user_data_dir" pointed to ~/.config/... on Linux. "user_config_dir" was only introduced in appdirs=1.3.0 and "user_data_dir" points to ~/.local/share/... in those versions. To retain the previous ~/.config/... usage, we now use the semantically better fitting "platformdirs.user_config_dir" instead.
----
The same issue was reported for `conda` by @s22chan in https://github.com/conda/conda/issues/13517 with @jezdez working on a fix in https://github.com/conda/conda/issues/13520 .
> Restore default user config search path on Linux

- .github/workflows/check-master.yml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
> ci: Use GITHUB_OUTPUT envvar instead of set-output command

- Makefile
- requirements-extra.txt
Fixes the local development setup command:
* Refactors the `make init` target to use a local prefix-based conda environment
* Adds a missing extra dependency on `ruamel.yaml` to fix `make test`
> fix: local development setup via `make init`

- binstar_client/commands/upload.py
I noticed that when running `anaconda upload --help` it would print out a bit of reStructuredText instead of plain output. Turns out it was hardcoded in the docstring of the `upload` command module.
Also fixed the URLs of the links.
> Updated links in upload help text

- binstar_client/plugins.py
- requirements-dev.txt
- tests/test_cli.py
This PR fixes a bug related to the passing of top-level CLI options into `binstar_main`.
Specifically, when running commands like:
* `anaconda --token TOKEN whoami`
* `anaconda --token TOKEN org whoami`
Since we would like both of those commands to be handled by `binstar_main`, while allowing the top-level entrypoint to be handled by `anaconda-cli-base`, we need some special handling of the top-level options (`--token`, `--site`, etc.).
For now, we just simply pass through `sys.argv` (with the optional `org` subcommand removed). This allows us to have completely backwards-compatible behavior. When we replace subcommands with click/typer-based alternatives, we can pass through these top-level options via the context (`ctx`) object, but for now this solution should be sufficient.
> fix: Manually handle `sys.argv` to allow proper delegation to `binstar_main`

- .github/workflows/check-master.yml
- .gitignore
- NOTES.md
- binstar_client/commands/download.py
- binstar_client/commands/notebook.py
- binstar_client/commands/upload.py
- binstar_client/deprecations.py
- tests/test_upload.py
Notebooks, projects, and environments have been removed from anaconda.org. This PR replaces the implementation of the `anaconda notebook ...` subcommand with a helpful error message and exits with a system error code of 1. We will remove this code at some point down the line.
The other support for these removed artifact types are embedded within the `upload` and `download` subcommands, so their removal from `anaconda-client` is deferred for now.
> Raise error on deprecated `notebook` subcommand

- .github/workflows/check-master.yml
- binstar_client/inspect_package/conda.py
- binstar_client/utils/config.py
- binstar_client/utils/notebook/data_uri.py
- conda.recipe/meta.yaml
- tests/inspect_package/test_conda.py
Conda packages can have permissions that prevent this temporary directory from being deleted, causing errors. Use the much more efficient streaming strategy to do it all in memory.
Before this, the icon feature could not have possibly worked. Will this cause problems now that it might work? However [almost no packages use icons.](https://metayaml-conda.fly.dev/metayaml?sql=select+package%2C+index_json+from+repodata_packages+where+json_extract%28index_json%2C+%27%24.icon%27%29+group+by+json_extract%28index_json%2C+%27%24.name%27%29)
I had trouble running pytest, with a lot of UnicodeDecodeError `FAILED binstar_client/inspect_package/tests/test_conda.py::Test::test_conda - UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 10: invalid start byte`
After fixing binary …
> Use conda package streaming

- binstar_client/utils/logging_utils.py
We have instead fixed the way logging is initialized inside `anaconda-cli-base` so we no longer need this patch/hack.
> chore: Remove logging hack

- binstar_client/commands/upload.py
Adds a note to explain that the `--keep-basename` option only applies to conda packages, and not standard Python packages.
Closes #707.
> Improve description for `--keep-basename` option on `anaconda upload` subcommand

- tests/utils/test_parse_specs.py
- tests/utils/test_spec.py
Adding a test in attempt to reproduce the error in https://github.com/anaconda/anaconda-client/issues/642. It appears the bug was fixed in the past, but it's still valuable to add a small test.
Resolves #642
> Add test to cover parse_specs

- .github/workflows/check-master.yml
- binstar_client/commands/authorizations.py
- binstar_client/commands/channel.py
- binstar_client/commands/config.py
- binstar_client/commands/copy.py
- binstar_client/commands/download.py
- binstar_client/commands/groups.py
- binstar_client/commands/move.py
- binstar_client/commands/package.py
- binstar_client/commands/remove.py
- binstar_client/commands/search.py
- binstar_client/commands/show.py
- binstar_client/commands/update.py
- binstar_client/commands/upload.py
- binstar_client/plugins.py
- binstar_client/utils/spec.py
- requirements-dev.txt
- tests/test_cli.py
> Note: these changes were first merged in #723 but were reverted before the 1.13.0 release. This PR is a fresh rebase of the same changes summarized below.
As part of the move toward the typer-based CLI defined in `anaconda-cli-base`, this PR adds a new typer subcommand for each of the existing subcommands. These are only mounted if the `ANACONDA_CLI_FORCE_NEW=true` environment variable is set.
Currently, the default state will either be the legacy CLI (if `anaconda-client` is the only plugin installed, or if `ANACONDA_CLIENT_FORCE_STANDALONE=true`, or to use the light typer subcommand wrapper, which just allows `anaconda-client` to be compatible as a plugin, while delegating all argument parsing and handling to the legacy `argparse` parser.
But, if `ANACONDA_CLI_FORCE_NEW=true`, then …
> feat: Add optional typer subcommands

- pyproject.toml
- setup.cfg
Moves the settings for `mypy` and `pytest` from `setup.cfg` into `pyproject.toml`. Also, simplifies the `mypy` settings to the minimal number of overrides to match current behavior.
> chore: Move mypy and pytest settings to `pyproject.toml`

- .github/workflows/check-master.yml
> chore: Replace Python 3.8 with 3.13 in the test matrix
