anaconda/anaconda-client

example-packages/notebooks/hello_binstar.ipynb
The notebook has:
```
print("Hello Binstar")
```
=> Add ipynb example package

binstar_client/inspect_package/ipynb.py, binstar_client/tests/test_ipynb.py
Not every notebook has signature, removing from now, will consider adding again if we think it will add value
=> Remove signature from notebooks

runtests.sh
run `./runtests.sh` and start developing!
=> Add TDD script

binstar_client/tests/test_login.py, binstar_client/utils/notebook/data_uri.py
=> Going back to green

example-packages/pypi/.binstar.yml
=> correct minimal typo

conda.recipe/bld.bat, conda.recipe/meta.yaml
=> Hot fix/win build

binstar_client/commands/login.py
fixes https://github.com/Anaconda-Server/anaconda-server/issues/404
=> change error to warning

binstar_client/inspect_package/conda.py, binstar_client/tests/test_subdir.py
This PR adds a function `get_subdir()`, and also adds tests and documentation.
=> Cleanup subdir

README.md, binstar_client/commands/authorizations.py, binstar_client/commands/config.py, binstar_client/commands/copy.py, binstar_client/commands/notebook.py, binstar_client/commands/remove.py, binstar_client/commands/search.py, binstar_client/commands/show.py, binstar_client/commands/upload.py, binstar_client/scripts/cli.py, setup.py
=> New name anaconda-client

binstar_client/commands/authorizations.py
This fixes Anaconda-Server/anaconda-server#609
=> Show correct username in warning 

binstar_client/__init__.py, binstar_client/commands/whoami.py, binstar_client/scripts/cli.py, binstar_client/utils/__init__.py
* Improved debug logging handlers
* Added debug logging statements
* Fix user-agent
@rafaelhbarros can you review?
=> Misc Fixes while debugging another issue

binstar_client/errors.py, binstar_client/utils/notebook/data_uri.py, conda.recipe/meta.yaml, setup.py
`pillow` you will only need pillow if you need to upload a thumbnail.
AS-784
=> [WIP] pillow is not a hard dependency anymore

binstar_client/commands/download.py, binstar_client/commands/notebook.py
=> Deprecate anaconda notebook download

binstar_client/inspect_package/ipynb.py, binstar_client/utils/notebook/uploader.py
=> Changed auto-version string to only use DOT instead of DASH

binstar_client/commands/notebook.py
I don't think we should release the deprecations warnings now.
=> Remove deprecation warnings.

binstar_client/scripts/cli.py
=> fix remove syslog handler

conda.recipe/meta.yaml
Closes Anaconda-Server/Anaconda-Server#1015
=> change conda.recipe to fix build issue

binstar_client/commands/authorizations.py, binstar_client/commands/upload.py
=> fix links for new docs

binstar_client/__init__.py
Fix downloading notebook from anaconda server without S3 storage.
Issue #250
=> PR: Download notebook should work with file storage

binstar_client/commands/channel.py, binstar_client/commands/copy.py, binstar_client/commands/upload.py
related to anaconda-server/anaconda-server#1313
=> added deprecation warnings and label names

binstar_client/commands/notebook.py
=> fix notebook usage spacing

binstar_client/commands/config.py, binstar_client/commands/upload.py
=> added auto-register config option

binstar_client/commands/remove.py
Re: Anaconda-server/anaconda-server#54 Anaconda-Server/docs.anaconda.org#63
Just show a simple error if things cannot be deleted or the command is not understood.
=> Show an error when not deleting or failing to delete data

binstar_client/__init__.py, binstar_client/commands/login.py, binstar_client/tests/test_login.py, binstar_client/tests/urlmock.py
Related to Anaconda-Server/Anaconda-server#1597 Anaconda-Server/Anaconda-server#1566
=> Add kerberos support to `anaconda login`

binstar_client/commands/upload.py, binstar_client/inspect_package/env.py, binstar_client/inspect_package/tests/data/environment.yml, binstar_client/inspect_package/tests/test_env.py, binstar_client/utils/detect.py
=> Upload environment files

binstar_client/inspect_package/pypi.py, binstar_client/inspect_package/tests/test_pypi.py
Fix tests for pip 8.1
@dsludwig
=> Fix tests for pip 8.1 (py27)

binstar_client/tests/test_copy.py
@malev 
Adds unit-tests for #304
=> Add test for `anaconda copy`

binstar_client/inspect_package/ipynb.py, binstar_client/inspect_package/tests/test_ipynb.py, binstar_client/utils/detect.py
Fixes bug uploading filenames with unicode chars #227
=> Decode bytes in filename

binstar_client/utils/projects/uploader.py
=> Projects won't have labels after all

binstar_client/utils/projects/models.py, binstar_client/utils/projects/tests/test_models.py
When running:
```
anaconda upload .
```
Fails!, **BAD**
now it can guess the name of the current dir, so `anaconda upload .` works 😄 💯 
@mmarchetti @srossross
=> Guess name when current dir

binstar_client/utils/projects/uploader.py
https://github.com/Anaconda-Platform/anaconda-server/pull/2112
=> Rename URL to use plural

binstar_client/utils/projects/models.py, binstar_client/utils/projects/tests/test_models.py
Closes https://github.com/Anaconda-Platform/anaconda-server/issues/2160
=> Fix files count

.binstar.yml, binstar_client/tests/data/bar/kapsel.yml, binstar_client/tests/data/bar/project.yml, binstar_client/utils/projects/__init__.py
=> Switch from anaconda_project to conda_kapsel API

binstar_client/commands/remove.py
Hopefully greater clarity on the command for newbies like myself
=> Minor edit to in-line help to expand explanation

binstar_client/utils/__init__.py, binstar_client/utils/config.py
Just moving code around in preparation for a deeper refactor.
=> Move configuration into separate module

conda.recipe/meta.yaml
Require minimum clyent version
=> Strict version

binstar_client/commands/upload.py, binstar_client/tests/test_upload.py
Adds `--private` option to create a package as private directly from the command line.
=> allows to upload private packages

binstar_client/__init__.py, binstar_client/commands/upload.py, binstar_client/inspect_package/conda.py, binstar_client/inspect_package/tests/test_conda.py
Sends more metadata on the release request
=> Send release attributes

binstar_client/commands/upload.py, binstar_client/scripts/cli.py, binstar_client/utils/__init__.py
Since conda stoped disabling `binstar` logger we've been having excessive logging.
What i've done is disable it ourselves and fix the parts where it wasn't being logged correctly.
=> Handling excesive logging

binstar_client/commands/upload.py
Closes #66 
Runs `conda convert -p all` to generate packages for all platforms and uploads all of them.
=> added --all option to upload command to convert files

.travis.yml, appveyor.yml
Adds the environment variables to the broken CI environments
=> Fixes CI issues

binstar_client/inspect_package/env.py
Added seconds on the environment version in case the user updates it within the minute.
=> Using seconds on environment version

CHANGELOG.md, binstar_client/inspect_package/tests/test_conda.py, binstar_client/inspect_package/tests/test_env.py, binstar_client/inspect_package/tests/test_ipynb.py, binstar_client/inspect_package/tests/test_pypi.py, binstar_client/inspect_package/tests/test_r.py, binstar_client/tests/fixture.py, binstar_client/tests/test_register.py, binstar_client/tests/test_upload.py, binstar_client/tests/test_whoami.py, binstar_client/utils/notebook/tests/test_base.py, binstar_client/utils/notebook/tests/test_data_uri.py, binstar_client/utils/notebook/tests/test_downloader.py, binstar_client/utils/test/utils.py
Closes #242 
It uses a single definition of function data_dir/data_path
=> Refactor data_dir function

CHANGELOG.md, binstar_client/commands/authorizations.py
If the server uses kerberos authentication do not attempt to re-login to get a named token.
=> Fixed kerberos token create

CHANGELOG.md, binstar_client/__init__.py
Fixes #416
Escapes file basename on uploads.
=> Escaping special characters when uploading files

CHANGELOG.md, binstar_client/utils/pprint.py
Closes #380 
Checks that there are no None elements when trying to join elements in a string.
=> Fixed pprint issue

binstar_client/commands/upload.py, binstar_client/scripts/cli.py
Fix upload error message when package types is empty.
=> Fix upload log message

binstar_client/utils/config.py, binstar_client/utils/test/test_config.py
Fixes #464 
Fixes https://github.com/ContinuumIO/navigator/issues/1501
---
Waiting for tests to pass @abarto
=> PR: Fix default config behavior

binstar_client/commands/download.py, binstar_client/commands/upload.py, binstar_client/utils/config.py, binstar_client/utils/notebook/downloader.py
=> PR: Add option to download specific package type

binstar_client/scripts/cli.py
=> PR: Fix typos on the help

.circleci/config.yml, .travis.yml, requirements.txt
=> PR: Update to circle ci 2

binstar_client/commands/upload.py
=> PR: Add skip-existing flag to upload command

binstar_client/commands/upload.py
Corrected links to upload documentation
=> Corrected links to documentation

CHANGELOG.md, binstar_client/commands/upload.py
Added summary and description from args to release_attributes, so they will be displayed on anaconda.org
=> AC-93: Fix summary and description arguments

binstar_client/__about__.py, binstar_client/utils/projects/__init__.py, requirements-dev.txt, requirements.txt, setup.cfg
Optional requirement moved to development requirements.
=> AC-87: fix for anaconda-project requirement

binstar_client/__about__.py, binstar_client/requests_ext.py, binstar_client/utils/notebook/__init__.py
Version bump also includes a fix of a bug with 'utf-8' decoding of downloaded file.
Dev-tested locally on Ubuntu machine.
=> AC-87: Fixes and version bump to 1.8.0

CHANGELOG.md
CHANGELOG updated and now includes all changes, that were implemented in 1.8.0.
=> AC-105: Changelog update

binstar_client/commands/upload.py
=> fix string formatting on interactive input

binstar_client/utils/config.py
Original issue was not reproduced. This is what looks like a possible fix for the issue (missing slash between user folder and .continuum).
dev-tested on a linux-64 machine
=> NAV-649: possible fix for permission denied issue

binstar_client/commands/authorizations.py, binstar_client/commands/upload.py, setup.py
* Update references to Anaconda Cloud or cloud to Anaconda.org.
* Update link to using tokens.
=> update references to Anaconda.org

.github/workflows/check-master.yml, binstar_client/errors.py, binstar_client/scripts/cli.py, conda.recipe/meta.yaml, requirements.txt
Fixes gh-689
This pulls in the code from https://github.com/anaconda-graveyard/clyent/blob/02b1eeb23a02c7d1ec64262c187eac013954fa45/clyent/__init__.py#L32-L143 with only minimal adjustments.
https://github.com/Anaconda-Platform/anaconda-client/commit/c3150186451dda38284186700e8db9b0cc9aa520 is actually a verbatim copy of that code.
N.B.: If code style, annotation, or other changes are desired, please feel free to push to this PR's branch (i.e., "Allow edits by maintainers" is checked).
=> Support Python 3.12

binstar_client/utils/config.py
It looks like a merge issue caused a duplication of code in `binstar_client.utils.config`.
=> Remove duplicate import
